language: cpp
compiler: 
  - gcc

sudo: false

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_REF: https://github.com/MemSadePeSade/redactor.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
  - cd docs
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  local_dir: /docs/html
  on:
    branch: master

  provider: script
  skip_cleanup: true
  script:
  - curl -T redactor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uyhwh:$BINTRAY_API_KEY "https://api.bintray.com/content/yhwh/otus/redactor/$TRAVIS_BUILD_NUMBER/redactor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"


 